name: Build and Deploy
on:
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - 'main'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: pulling git repo
              uses: actions/checkout@v2
            - name: testing
              run: echo "testing ubuntu"
            - name: installing python on the virtual ubuntu
              uses: actions/setup-python@v2
              with:
                python-version: '3.10' 
            - name: update pip
              run: python -m pip install --upgrade pip
            - name: install depedencies
              run: pip install -r requirements.txt
            - name: testing pytest
              run: |
                pip install pytest
                pytest