name: Build and Deploy

on:
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - 'main'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: pullig git repo
              uses: actions/checkout@v3
            - name: CI/CD Pipeline
              run: echo"testing CI/CD Pipeline"