name: Build and Deploy
on:
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - 'main'
jobs:
    build:
        environment:
            name: pyfastapi
        env:
            DB_HOST: ${{secrets.DB_HOST}}
            DB_PORT: ${{secrets.DB_PORT}}
            DB_USERNAME: ${{secrets.DB_USERNAME}}
            DB_PASSWORD: ${{secrets.DB_PASSWORD}}
            DB_NAME: ${{secrets.DB_NAME}}
            SECRET_KEY: ${{secrets.SECRET_KEY}}
            ALGORITHM: ${{secrets.ALGORITHM}}
            TOKEN_EXPIRE_TIME_MINUTES: ${{secrets.TOKEN_EXPIRE_TIME_MINUTES}}
        runs-on: ubuntu-latest
        steps:
            - name: pulling git repo
              uses: actions/checkout@v2
            - name: testing
              run: echo "testing ubuntu"
            - name: installing python on the virtual ubuntu
              uses: actions/setup-python@v2
              with:
                python-version: '3.10' 
            - name: update pip
              run: python -m pip install --upgrade pip
            - name: install depedencies
              run: pip install -r requirements.txt