name: Build and Deploy

on:
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - 'main'
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: pullig git repo
              uses: actions/checkout@v3